version: "3.8"

services:
  config-service:
    container_name: config-service
    image: grillitoxc/configservice:latest
    ports:
      - 8081:8081

  eureka-service:
    container_name: eureka-service
    image: grillitoxc/eurekaservice:latest
    ports:
      - 8761:8761

  employee-db:
      container_name: employee-db
      image: postgres:latest
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=MueblesStgo
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=93304596
      depends_on:
        - config-service
        - eureka-service
      volumes:
        - /var/lib/postgresql/data

  gateway-service:
    container_name: gateway-service
    image: grillitoxc/gatewayservice:latest
    ports:
      - 8080:8080
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
    depends_on:
      - config-service
      - eureka-service
      - employee-db
    links:
      - eureka-service