version: "3.7"

services:
  employee-db:
      container_name: employee-db
      image: postgres:latest
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=mueblesstgo-employee
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=93304596
      volumes:
        - /var/lib/postgresql/data

  config-service:
    container_name: config-service
    image: grillitoxc/configservice:latest
    ports:
      - "8081:8081"

  eureka-service:
    container_name: eureka-service
    image: grillitoxc/eurekaservice:latest
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    environment:
      - spring.cloud.config.uri=http://config-service:8081

  employee-service:
    container_name: employee-service
    image: grillitoxc/employeeservice:latest
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://employee-db:5432/mueblesstgo-employee
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=93304596
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - config-service
      - eureka-service
      - employee-db
    links:
      - eureka-service
