spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mueblesstgo-clock
    username: postgres
    password: 93304596
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload-dir: ./src/main/resources/static/uploads
server:
  port: 8094
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}