spring:
  datasource:
    url: postgresql://localhost:5432/mueblesstgo-employee
    username: postgres
    password: 93304596
  jpa:
    hibernate:
      ddl-auto: auto
keycloak:
  realm: MueblesStgo-MicroServices
  auth-server-url: http://host.docker.internal:8082
  resource: gateway-service
  public-client: true
  bearer-only: true
server:
  port: 8091
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}