spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mueblesstgo-spreadsheet
    username: postgres
    password: 93304596
  jpa:
    hibernate:
      ddl-auto: update
keycloak:
  realm: MueblesStgo-MicroServices
  auth-server-url: http://localhost:8082
  resource: gateway-service
  public-client: true
  bearer-only: true
server:
  port: 8095
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}