server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          timeout: 10000
          default-label: main
          uri: https://github.com/Grillitoxc/MueblesStgo-MicroServices
          search-paths: config-data
          force-pull: true
  application:
    name: config-service